import { Article } from './types';

export const ARTICLES: Article[] = [
  {
    id: 1,
    title: 'Будущее UI/UX: Дизайн на основе ИИ',
    excerpt: 'Узнайте, как искусственный интеллект революционизирует способы проектирования пользовательских интерфейсов, создавая более персонализированные и интуитивно понятные впечатления.',
    author: 'Мұхамаден Үрістем',
    authorImageUrl: 'https://placehold.co/100x100/000000/000000.png',
    date: '1 октября 2025',
    imageUrl: 'https://picsum.photos/seed/futureai/1200/800',
    category: 'UI/UX Дизайн',
    readTime: 8,
  },
  {
    id: 2,
    title: 'Глубокое погружение в новые возможности React 18',
    excerpt: 'От конкурентного рендеринга до автоматического пакетирования — мы разбираем самые значимые нововведения в React 18 и как они могут улучшить производительность вашего приложения.',
    author: 'Иван Петров',
    authorImageUrl: 'https://picsum.photos/id/1005/100/100',
    date: '24 сентября 2025',
    imageUrl: 'https://picsum.photos/seed/react18/800/600',
    category: 'React',
    readTime: 12,
  },
  {
    id: 3,
    title: 'Освоение Tailwind CSS для быстрой разработки',
    excerpt: 'Изучите основные концепции utility-first CSS и посмотрите, как Tailwind может значительно ускорить ваш процесс стилизации без написания единой строки пользовательского CSS.',
    author: 'Алексей Сидоров',
    authorImageUrl: 'https://picsum.photos/id/1011/100/100',
    date: '22 сентября 2025',
    imageUrl: 'https://picsum.photos/seed/tailwind/800/600',
    category: 'CSS',
    readTime: 7,
  },
  {
    id: 4,
    title: 'Расцвет бессерверной архитектуры',
    excerpt: 'Является ли бессерверная архитектура будущим бэкенд-разработки? Мы взвешиваем плюсы и минусы перехода на бессерверную модель и исследуем популярные платформы.',
    author: 'Елена Белова',
    authorImageUrl: 'https://picsum.photos/id/1012/100/100',
    date: '20 сентября 2025',
    imageUrl: 'https://picsum.photos/seed/serverless/800/600',
    category: 'Бэкенд',
    readTime: 10,
  },
    {
    id: 5,
    title: 'TypeScript для начинающих: почему стоит перейти',
    excerpt: 'Устали от ошибок во время выполнения? Узнайте, как статическая типизация TypeScript может помочь вам выявлять ошибки на ранней стадии и писать более поддерживаемый код.',
    author: 'Крис Зеленов',
    authorImageUrl: 'https://picsum.photos/id/1025/100/100',
    date: '18 сентября 2025',
    imageUrl: 'https://picsum.photos/seed/typescript/800/600',
    category: 'JavaScript',
    readTime: 9,
  },
  {
    id: 6,
    title: 'Эффективное управление состоянием в крупных React-приложениях',
    excerpt: 'Context API, Redux, Zustand или что-то еще? В этой статье сравниваются различные решения для управления состоянием в сложных приложениях на React.',
    author: 'Светлана Браун',
    authorImageUrl: 'https://picsum.photos/id/1028/100/100',
    date: '15 сентября 2025',
    imageUrl: 'https://picsum.photos/seed/statemgmt/800/600',
    category: 'React',
    readTime: 15,
  },
];